#!/usr/bin/env bash
# Blocks destructive commands in ai-local-agent-tools.
# Claude Code hook: PreToolUse[Bash]

INPUT=$(cat)
CMD=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('command',''))" 2>/dev/null)

DESTRUCTIVE_PATTERNS=(
  "docker stack rm"
  "docker swarm leave"
  "docker service rm"
  "docker system prune"
  "docker volume rm"
  "git push --force"
  "git push -f"
  "rm -rf data/"
  "rm -rf logs/"
  "DROP TABLE"
  "DELETE FROM"
)

for pattern in "${DESTRUCTIVE_PATTERNS[@]}"; do
  if echo "$CMD" | grep -qi "$pattern"; then
    echo "BLOCKED: '$pattern' requires explicit human confirmation." >&2
    echo "Show the full command to the user and ask for approval." >&2
    exit 2
  fi
done

# Block editing .env directly
if echo "$CMD" | grep -qE "(nano|vim|vi|echo.*>|tee)\s+docker/\.env"; then
  echo "BLOCKED: docker/.env is generated by Ansible (hp1-infra)." >&2
  echo "Edit vault/group_vars in hp1-infra and re-run the playbook instead." >&2
  exit 2
fi

exit 0
